// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxnabrwoknlixhmeilho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bmFicndva25saXhobWVpbGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Nzg4NTAsImV4cCI6MjA2NTA1NDg1MH0.3N2bulJqkNqhXSJG2_Dprb0zPb2uqbDoX2018VpHEEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);